server:
  port: 8090

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: accounts
          uri: lb://MSVC-ACCOUNTS
          predicates:
            - Path=/accounts/**
          filters:
            - name: JwtForwardingFilterFactory
            
        - id: users
          uri: lb://MSVC-USERS
          predicates:
            - Path=/users/**
            
        - id: usersAccountsManager-manager
          uri: lb://MSVC-USERSACCOUNTSMANAGER
          predicates:
            - Path=/manager/**
        - id: usersAccountsManager-auth
          uri: lb://MSVC-USERSACCOUNTSMANAGER
          predicates:
            - Path=/auth/**
            
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.cloud.gateway.route: DEBUG
    org.springframework.http.server.reactive: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka/  # Dirección del Eureka en Docker

# Propiedad de prueba
test:
  message: "El archivo de configuración msvc-gateway-dev.yml está siendo utilizado correctamente. Desde Docker."
