server:
  port: 8085

spring:
  application:
    name: msvc-cards

  datasource:
    url: jdbc:mysql://localhost:3306/dmh_bd1
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Alternativa: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #dialect ya no se usa, spring boot lo detecta automáticamente
        #dialect: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://localhost:8761
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}


springdoc:
  swagger-ui:
    path: /swagger-ui.html # swagger-ui custom path
  api-docs:
    path: /api-docs # /api-docs endpoint custom path

# Propiedad de prueba
test:
  message: "El archivo de configuración msvc-cards.yml está siendo utilizado correctamente. Desde Github para localhost"
