server:
  port: 8081

spring:
  application:
    name: msvc-usersAccountsManager

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/dmh_bd1  # Conectar a MySQL usando host.docker.internal
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Ajuste de HikariCP para mejorar la gestión de conexiones y evitar cierres inesperados
    hikari:
      maximum-pool-size: 10  # Número máximo de conexiones en el pool
      minimum-idle: 5  # Número mínimo de conexiones inactivas
      idle-timeout: 30000  # Tiempo en milisegundos antes de que una conexión inactiva sea removida
      max-lifetime: 1800000  # Tiempo máximo de vida de una conexión (30 minutos)
      connection-timeout: 20000  # Tiempo máximo de espera para obtener una conexión (20 segundos)

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update  # Mantiene la base de datos actualizada en desarrollo
    show-sql: true  # Muestra las consultas SQL en la consola para depuración

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env"  # Exponer los endpoints de Actuator
  endpoint:
    health:
      show-details: always  # Mostrar detalles completos en /actuator/health

springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI custom path
  api-docs:
    path: /api-docs  # Custom path for API docs

feign:
  client:
    config:
      default:
        loggerLevel: full  # Configura el nivel de logs de Feign para mostrar todas las solicitudes

eureka:
  client:
    register-with-eureka: true  # Registra este microservicio en Eureka
    fetch-registry: true  # Obtiene el registro de otros servicios de Eureka
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka/  # URL del servidor Eureka
  instance:
    prefer-ip-address: true  # Usar la IP preferida
    instance-id: ${spring.application.name}:${random.value}  # ID único de la instancia


# Configuración de logs
logging:
  level:
    root: INFO  # Nivel global de logging, puedes cambiarlo a DEBUG si lo necesitas
    com.DigitalMoneyHouse.msvc_usersAccountsManager.controller: DEBUG  # Para el controlador
    com.DigitalMoneyHouse.msvc_usersAccountsManager.service: DEBUG  # Para el servicio
    com.DigitalMoneyHouse.msvc_usersAccountsManager.repository: INFO  # Puedes ajustar según el detalle que necesites
    org.springframework.web: DEBUG  # Mostrar logs detallados de Spring Web (opcional)
    org.springframework.cloud.openfeign: DEBUG  # Para ver detalles de las solicitudes de Feign (opcional)
    org.hibernate.SQL: DEBUG  # Mostrar las consultas SQL generadas (opcional)


# Propiedad de prueba
test:
  message: "--Profile: dev - El archivo de configuración msvc-usersAccountsManager-dev.yml está siendo utilizado correctamente. Desde Github"
